#!/usr/bin/env python3
"""
Generate the GPT-2 / Qwen byte-level alphabet table as a C array.

The byte-level encoding maps each byte 0-255 to a unique unicode character
so that all bytes (including control chars) are representable as printable text.
This matches the standard GPT-2 / HuggingFace byte_to_unicode() mapping.
"""

import sys


def byte_to_unicode():
    """Reproduces the HuggingFace tokenizers byte_to_unicode() function."""
    bs = (
        list(range(ord("!"), ord("~") + 1))
        + list(range(ord("\xa1"), ord("\xac") + 1))
        + list(range(ord("\xae"), ord("\xff") + 1))
    )
    cs = bs[:]
    n = 0
    for b in range(256):
        if b not in bs:
            bs.append(b)
            cs.append(256 + n)
            n += 1
    return dict(zip(bs, [chr(c) for c in cs]))


def char_to_c_string(ch: str) -> str:
    """Convert a unicode char to a C string literal with proper escaping."""
    utf8_bytes = ch.encode("utf-8")
    parts = []
    for b in utf8_bytes:
        if b == ord('"'):
            parts.append('\\"')
        elif b == ord("\\"):
            parts.append("\\\\")
        elif 32 <= b <= 126:
            parts.append(chr(b))
        else:
            parts.append(f"\\{b:03o}")
    return '"' + "".join(parts) + '"'


def main():
    mapping = byte_to_unicode()

    out = []
    out.append("/* Auto-generated by tools/gen_byte_table.py — do not edit. */")
    out.append("/* GPT-2/Qwen byte-level alphabet: byte → unicode string (UTF-8) */")
    out.append("static const char *qw6_byte_chars[] = {")

    for i in range(256):
        literal = char_to_c_string(mapping[i])
        if i < 255:
            literal += ","
        out.append(f"    {literal}")

    out.append("};")
    out.append(f"/* 256 entries, bytes 0-255 */")

    print("\n".join(out))


if __name__ == "__main__":
    main()